app/blueprints/shop/models.py
from app import db

class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    image = db.Column(db.String)
    price = db.Column(db.Float)
    description = db.Column(db.Text)

class Cart(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    product_key = db.Column(db.String)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    quantity = db.Column(db.Integer)

app/blueprints/shop/__init__.py
from flask import Blueprint

bp = Blueprint('shop', __name__, url_prefix='/shop')

from .import models, routes

app/blueprints/shop/routes.py
from flask.templating import render_template
from werkzeug.utils import redirect
from .import bp as shop
from .models import Product, Cart
from flask import redirect, url_for, flash, current_app as app
import stripe
from flask_login import current_user
from app import db


@shop.route('/')
def index():
    print(current_user.get_id())
    stripe.api_key = app.config.get('STRIPE_TEST_SK')
    context = {
        'products': stripe.Product.list()
    }
    return render_template('shop/index.html', **context)

@shop.route('/product/add/<id>')
def add_product(id):
    cart_item = Cart.query.filter_by(product_key=str(id)).filter_by(user_id=current_user.get_id()).first()
    # if cart item already exists, increment its quantity by 1 and UPDATE the database
    if cart_item:
        cart_item.quantity += 1
        db.session.commit()
        flash('Product added successfully', 'success')
        return redirect(url_for('shop.cart'))
    # otherwise, create the new item and add it to the database
    cart_item = Cart(product_key=id, user_id=current_user.get_id(), quantity=1)
    db.session.add(cart_item)
    db.session.commit()
    flash('Product added successfully', 'success')
    return redirect(url_for('shop.index'))


@shop.route('/cart/remove/<id>')
def remove_product(id):
    Cart.query.filter_by(product_key=str(id)).filter_by(user_id=current_user.get_id()).delete()
    db.session.commit()
    flash('Product deleted successfully', 'success')
    return redirect(url_for('shop.cart'))
    
@shop.route('/cart')
def cart():
    stripe.api_key = app.config.get('STRIPE_TEST_SK')
    cart_items = []
    for i in Cart.query.filter_by(user_id=current_user.get_id()).all():
        stripe_product = stripe.Product.retrieve(i.product_key)
        product_dict = {
            'product': stripe_product,
            'price': float(stripe.Price.retrieve(stripe_product['metadata']['price_id'])['unit_amount']) / 100,
            'quantity': i.quantity
        }
        cart_items.append(product_dict)
    context = {
        'cart': cart_items
    }
    return render_template('shop/cart.html', **context)

@shop.route('/checkout', methods=['POST'])
def create_checkout_session():
    stripe.api_key = app.config.get('STRIPE_TEST_SK')
    items = []
    for i in Cart.query.filter_by(user_id=current_user.get_id()).all():
        stripe_product = stripe.Product.retrieve(i.product_key)
        product_dict = {
            'price': stripe.Price.retrieve(stripe_product['metadata']['price_id']),
            'quantity': i.quantity
        }
        items.append(product_dict)
    try:
        checkout_session = stripe.checkout.Session.create(
            line_items=items,
            mode='payment',
            success_url='http://localhost:5000/shop/success',
            cancel_url='http://localhost:5000/shop/cancel',
        )
    except Exception as error:
        return str(error)
    return redirect(checkout_session.url, code=303)

@shop.route('/success/')
def clear_cart():
    Cart.query.filter_by(product_key=str(id)).filter_by(user_id=current_user.get_id()).delete()
    db.session.commit()
    context = {
    }
    return render_template('shop/success.html', **context)

#     @shop.route('/cart/remove/<id>')
# def remove_product(id):
#     Cart.query.filter_by(product_key=str(id)).filter_by(
#         user_id=current_user.get_id()).delete()
#     db.session.commit()
#     flash('Product deleted successfully', 'success')
#     return redirect(url_for('shop.cart'))

app/templates/shop/cancel.html
<!DOCTYPE html>
<html>

<head>
    <title>Checkout canceled</title>
    <link rel="stylesheet" href="style.css">
</head>

<body>
    <section>
        <p>Forgot to add something to your cart? Shop around then come back to pay!</p>
    </section>
</body>

</html>

app/templates/shop/cart.html
{% extends 'layout.html' %}

{% block content %}

    <div>
        <h3>
            Cart
            <span class="float-right">
                <form action="{{ url_for('shop.create_checkout_session') }}" method="post">
                    <input id="checkout-button" type="submit" class="btn btn-primary" value="Checkout">
                </form>
            </span>
        </h3>
        <hr>

        <div class="card shopping-cart">
            <div class="card-header bg-dark text-light">
                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                Shopping Cart
                <a href="{{ url_for('shop.index') }}" class="btn btn-outline-info btn-sm pull-right">Continue Shopping</a>
                <div class="clearfix"></div>
            </div>
            <div class="card-body">
                
                {% for p in cart %}
                    <!-- PRODUCT -->
                    <div class="row">
                        <div class="col-12 col-sm-12 col-md-2 text-center">
                            <img class="img-responsive" src="{{ p.product.images[0] }}" alt="{{ p.product.name }}" height="80">
                        </div>
                        <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
                            <h4 class="product-name"><strong>{{ p.product.name }}</strong></h4>
                            <h4>
                                <small></small>
                            </h4>
                        </div>
                        <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row">
                            <div class="col-3 col-sm-3 col-md-6 text-md-right" style="padding-top: 5px">
                                <h6><strong>${{ p.price }} <span class="text-muted">x</span></strong></h6>
                            </div>
                            <div class="col-4 col-sm-4 col-md-4">
                                <div class="quantity">
                                    <input type="number" step="1" max="99" min="1" value="{{ p.quantity }}" title="Qty" class="qty" size="4">
                                </div>
                            </div>
                            <div class="col-2 col-sm-2 col-md-2 text-right">
                                <a href="{{ url_for('shop.remove_product', id=p.product.id) }}" button type="button" class="btn btn-outline-danger btn-xs">
                                    <i class="fa fa-trash" aria-hidden="true"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <!-- END PRODUCT -->
                
                
                <div class="pull-right">
                    <a href="{{ url_for('shop.add_product', id=p.product.id) }}" class="btn btn-outline-secondary pull-right">
                        Update Shopping Cart
                    </a>
                </div>
            </div>
            <div class="card-footer">
                <!-- <div class="coupon col-md-5 col-sm-5 no-padding-left pull-left">
                        <div class="row">
                            <div class="col-6">
                                <input type="text" class="form-control" placeholder="cupone code">
                            </div>
                            <div class="col-6">
                                <input type="submit" class="btn btn-default" value="Use cupone">
                            </div>
                        </div>
                    </div> -->
                <div class="text-right">
                    <div class="cart-totals">
                        Subtotal: <b>{{p.price * p.quantity}}</b>
                    </div>
                    <div class="cart-totals">
                        Tax: <b>{{p.price * p.quantity * 0.08}}</b>
                    </div>
                    <div class="cart-totals">
                        Grand total: <b>{{(p.price * p.quantity) + (p.price * p.quantity * 0.08)}}</b>
                    </div>
                </div>
            </div>
        </div>
{% endfor %}
    </div>

{% endblock content %}

app/templates/shop/index.html
{% extends 'layout.html' %}

{% block content %}

<div>
    <h3>Shop</h3>
    <hr>

        <div class="card-deck row">
            {% for p in products %}
                <div class="col-4">
                    <div class="card">
                        <img class="card-img-top" src="{{ p.images[0] }}" alt="{{ p.name }}">
                        <div class="card-body">
                            <h4 class="card-title">{{ p.name }}</h4>
                            <p class="card-text">{{ p.description|truncate(20, True) }}</p>
                        </div>
                        <div class="card-footer">
                            <a href="{{ url_for('shop.add_product', id=p.id) }}" class="btn btn-success btn-block">Add to Cart</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

</div>

{% endblock content %}

app/templates/shop/success.html
<!DOCTYPE html>
<html>

<head>
    <title>Thanks for your order!</title>
    <link rel="stylesheet" href="style.css">
</head>

<body>
    <section>
        <p>
            We appreciate your business! If you have any questions, please email
            <a href="mailto:orders@example.com">orders@example.com</a>.
        </p>
    </section>
</body>

</html>